# -*- mode: ruby -*-
# vi: set ft=ruby :

# This is the server beta for the LPIC-2 practices - CENTOS

Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/centos-6.6-64-puppet"

  config.vm.hostname = "beta"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :public_network, ip: "192.168.1.102", bridge: "en1: Wi-Fi (AirPort)"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |v|
    v.memory = 768
    v.cpus = 1
    v.gui = true
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  #   sudo rpm -ivh epel-release-6-8.noarch.rpm
  #   sudo yum groupinstall -y Xfce
  #   sudo yum  groupinstall -y Fonts
  #   sudo yum install -y xorg-x11-fonts-Type1 xorg-x11-fonts-misc
  # SHELL
end
